name: Build Debug APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v4 

      - name: Set up JDK 17
        uses: actions/setup-java@v4 
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' 

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate Debug APKs
        run: ./gradlew assembleDebug assembleDebug

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Upload Debug APKs to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          FULL_DEBUG_APK="app/build/outputs/apk/debug/app-debug.apk"

          if [ -f "$FULL_DEBUG_APK" ]; then
            echo "Uploading Full Debug APK..."
            curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id=${{ env.TELEGRAM_CHAT_ID }} \
            -F caption="Full Debug APK Build #${{ github.run_number }}" \
            -F document=@"$FULL_DEBUG_APK"
          else
            echo "Error: Full Debug APK not found at $FULL_DEBUG_APK."
          fi

        
